project:
  type: website

website:
  title: "Keith Karani"
  site-url: "keithkarani.tech"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/KaraniWachira
      - icon: twitter
        href: https://x.com/mrAfricanSeed
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      - sketchy
      - brand
    css: styles.css

editor: visual

